import {
    ShieldUser,
    Heart,
    ArrowLeft,
    ShieldPlus,
    Mail,
    Lock,
} from 'lucide-react';
import {
    IconPlus,
    IconTrash,
    IconWorld,
    IconAlertCircle,
    IconDeviceLaptop,
    IconSettings,
    IconLockPlus,
    IconLayoutDashboard,
    IconShieldLock,
    IconFingerprint,
    IconUsers,
    IconExternalLink,
    IconCopy,
    IconCheck,
    IconCircleCheck,
    IconBook,
    IconDownload,
    IconTerminal,
    IconEye,
    IconEyeOff,
    IconKey,
} from '@tabler/icons-react';

export default {
    Logo: ShieldUser,
    Heart: Heart,
    LeftArrow: ArrowLeft,
    ShieldPlus: ShieldPlus,
    Mail: Mail,
    Lock: Lock,
    Add: IconPlus,
    Trash: IconTrash,
    World: IconWorld,
    Alert: IconAlertCircle,
    Laptop: IconDeviceLaptop,
    Settings: IconSettings,
    LockPlus: IconLockPlus,
    Dashboard: IconLayoutDashboard,
    ShieldLock: IconShieldLock,
    Fingerprint: IconFingerprint,
    Users: IconUsers,
    Link: IconExternalLink,
    Copy: IconCopy,
    Check: IconCheck,
    CircleCheck: IconCircleCheck,
    Book: IconBook,
    Download: IconDownload,
    Terminal: IconTerminal,
    EyeOpen: IconEye,
    EyeClose: IconEyeOff,
    Key: IconKey,
};
